services:

  app:
    build: .
    ports:
      - "3004:3000"
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: pass123
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: